// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/club" | "/coachs" | "/coachs/[id]" | "/contact" | "/dashboard" | "/dashboard/admin" | "/dashboard/admin/courts" | "/dashboard/admin/courts/[id]/edit" | "/dashboard/admin/courts/new" | "/dashboard/admin/events" | "/dashboard/admin/events/[id]" | "/dashboard/admin/journal" | "/dashboard/admin/orders" | "/dashboard/admin/products" | "/dashboard/admin/products/[id]/edit" | "/dashboard/admin/products/new" | "/dashboard/admin/settings" | "/dashboard/analytics" | "/dashboard/coaches" | "/dashboard/coaches/[id]/edit" | "/dashboard/coaches/commissions" | "/dashboard/coaches/new" | "/dashboard/events" | "/dashboard/events/[id]" | "/dashboard/events/[id]/edit" | "/dashboard/events/new" | "/dashboard/fundraising" | "/dashboard/fundraising/[id]" | "/dashboard/fundraising/[id]/edit" | "/dashboard/fundraising/new" | "/dashboard/members" | "/dashboard/members/[id]" | "/dashboard/members/new" | "/dashboard/messages" | "/dashboard/notifications" | "/dashboard/partners" | "/dashboard/partners/[id]/edit" | "/dashboard/partners/new" | "/dashboard/payments" | "/dashboard/payments/[id]" | "/dashboard/reservations" | "/dashboard/reservations/new" | "/dashboard/settings" | "/dashboard/shop" | "/dashboard/shop/checkout" | "/dashboard/shop/orders" | "/dashboard/stringing" | "/evenements" | "/evenements/[id]" | "/login" | "/partenaires" | "/register" | "/tarifs"
type AppRouteHandlerRoutes = "/api/admin/courts" | "/api/admin/courts/[id]" | "/api/admin/events/[id]/csv" | "/api/admin/orders/[id]" | "/api/admin/products" | "/api/admin/products/[id]" | "/api/admin/settings" | "/api/admin/transactions/[id]" | "/api/admin/users" | "/api/admin/users/[id]" | "/api/admin/users/[id]/password" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/register" | "/api/coaches" | "/api/coaches/[id]" | "/api/coaches/[id]/reviews" | "/api/coaches/commissions" | "/api/contact" | "/api/events" | "/api/events/[id]" | "/api/events/[id]/register" | "/api/fundraising" | "/api/fundraising/[id]" | "/api/fundraising/[id]/donate" | "/api/health" | "/api/notifications" | "/api/partners" | "/api/partners/[id]" | "/api/partners/[id]/click" | "/api/partners/[id]/image" | "/api/payments/[id]/mtn" | "/api/payments/[id]/stripe" | "/api/payments/webhook" | "/api/profile" | "/api/reservations" | "/api/reservations/[id]" | "/api/reservations/availability" | "/api/shop/orders" | "/api/stringing" | "/api/stringing/[id]" | "/api/users/[id]" | "/uploads/[name]"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/admin/courts": {}
  "/api/admin/courts/[id]": { "id": string; }
  "/api/admin/events/[id]/csv": { "id": string; }
  "/api/admin/orders/[id]": { "id": string; }
  "/api/admin/products": {}
  "/api/admin/products/[id]": { "id": string; }
  "/api/admin/settings": {}
  "/api/admin/transactions/[id]": { "id": string; }
  "/api/admin/users": {}
  "/api/admin/users/[id]": { "id": string; }
  "/api/admin/users/[id]/password": { "id": string; }
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/register": {}
  "/api/coaches": {}
  "/api/coaches/[id]": { "id": string; }
  "/api/coaches/[id]/reviews": { "id": string; }
  "/api/coaches/commissions": {}
  "/api/contact": {}
  "/api/events": {}
  "/api/events/[id]": { "id": string; }
  "/api/events/[id]/register": { "id": string; }
  "/api/fundraising": {}
  "/api/fundraising/[id]": { "id": string; }
  "/api/fundraising/[id]/donate": { "id": string; }
  "/api/health": {}
  "/api/notifications": {}
  "/api/partners": {}
  "/api/partners/[id]": { "id": string; }
  "/api/partners/[id]/click": { "id": string; }
  "/api/partners/[id]/image": { "id": string; }
  "/api/payments/[id]/mtn": { "id": string; }
  "/api/payments/[id]/stripe": { "id": string; }
  "/api/payments/webhook": {}
  "/api/profile": {}
  "/api/reservations": {}
  "/api/reservations/[id]": { "id": string; }
  "/api/reservations/availability": {}
  "/api/shop/orders": {}
  "/api/stringing": {}
  "/api/stringing/[id]": { "id": string; }
  "/api/users/[id]": { "id": string; }
  "/club": {}
  "/coachs": {}
  "/coachs/[id]": { "id": string; }
  "/contact": {}
  "/dashboard": {}
  "/dashboard/admin": {}
  "/dashboard/admin/courts": {}
  "/dashboard/admin/courts/[id]/edit": { "id": string; }
  "/dashboard/admin/courts/new": {}
  "/dashboard/admin/events": {}
  "/dashboard/admin/events/[id]": { "id": string; }
  "/dashboard/admin/journal": {}
  "/dashboard/admin/orders": {}
  "/dashboard/admin/products": {}
  "/dashboard/admin/products/[id]/edit": { "id": string; }
  "/dashboard/admin/products/new": {}
  "/dashboard/admin/settings": {}
  "/dashboard/analytics": {}
  "/dashboard/coaches": {}
  "/dashboard/coaches/[id]/edit": { "id": string; }
  "/dashboard/coaches/commissions": {}
  "/dashboard/coaches/new": {}
  "/dashboard/events": {}
  "/dashboard/events/[id]": { "id": string; }
  "/dashboard/events/[id]/edit": { "id": string; }
  "/dashboard/events/new": {}
  "/dashboard/fundraising": {}
  "/dashboard/fundraising/[id]": { "id": string; }
  "/dashboard/fundraising/[id]/edit": { "id": string; }
  "/dashboard/fundraising/new": {}
  "/dashboard/members": {}
  "/dashboard/members/[id]": { "id": string; }
  "/dashboard/members/new": {}
  "/dashboard/messages": {}
  "/dashboard/notifications": {}
  "/dashboard/partners": {}
  "/dashboard/partners/[id]/edit": { "id": string; }
  "/dashboard/partners/new": {}
  "/dashboard/payments": {}
  "/dashboard/payments/[id]": { "id": string; }
  "/dashboard/reservations": {}
  "/dashboard/reservations/new": {}
  "/dashboard/settings": {}
  "/dashboard/shop": {}
  "/dashboard/shop/checkout": {}
  "/dashboard/shop/orders": {}
  "/dashboard/stringing": {}
  "/evenements": {}
  "/evenements/[id]": { "id": string; }
  "/login": {}
  "/partenaires": {}
  "/register": {}
  "/tarifs": {}
  "/uploads/[name]": { "name": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
