// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(site)/club/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/club">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/club/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/coachs/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coachs/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/coachs/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/coachs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coachs">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/coachs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/evenements/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/evenements/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/evenements/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/evenements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/evenements">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/evenements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/partenaires/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partenaires">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/partenaires/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/tarifs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tarifs">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/tarifs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/courts/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/courts/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/courts/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/courts/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/courts/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/courts/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/courts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/courts">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/courts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/events/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/events/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/events/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/events">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/journal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/journal">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/journal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/orders">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/products/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/products/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/products/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/products/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/products/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/products/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/products">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/coaches/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/coaches/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/coaches/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/coaches/commissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/coaches/commissions">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/coaches/commissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/coaches/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/coaches/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/coaches/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/coaches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/coaches">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/coaches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/events/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/events/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/events/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/events/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/events/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/events/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/fundraising/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/fundraising/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/fundraising/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/fundraising/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/fundraising/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/fundraising/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/fundraising/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/fundraising/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/fundraising/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/fundraising/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/fundraising">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/fundraising/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/members/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/members/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/members/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/members/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/members/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/members/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/members/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/members">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/members/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/messages">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/partners/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/partners/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/partners/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/partners/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/partners/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/partners/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/partners">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/payments/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/payments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/payments/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/payments">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/reservations/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reservations/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/reservations/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/reservations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reservations">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/reservations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/shop/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/shop/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/shop/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/shop/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/shop/orders">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/shop/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/shop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/shop">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/shop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/stringing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/stringing">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/stringing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/courts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/courts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/courts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/courts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/courts">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/courts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/events/[id]/csv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/events/[id]/csv">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/events/[id]/csv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/products/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/products/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/products/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/products">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/transactions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/transactions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/transactions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/[id]/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]/password">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/[id]/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/coaches/[id]/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coaches/[id]/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/api/coaches/[id]/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/coaches/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coaches/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/coaches/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/coaches/commissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coaches/commissions">> = Specific
  const handler = {} as typeof import("../../src/app/api/coaches/commissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/coaches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coaches">> = Specific
  const handler = {} as typeof import("../../src/app/api/coaches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../src/app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/[id]/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/[id]/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/[id]/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fundraising/[id]/donate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fundraising/[id]/donate">> = Specific
  const handler = {} as typeof import("../../src/app/api/fundraising/[id]/donate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fundraising/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fundraising/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/fundraising/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fundraising/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fundraising">> = Specific
  const handler = {} as typeof import("../../src/app/api/fundraising/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/partners/[id]/click/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partners/[id]/click">> = Specific
  const handler = {} as typeof import("../../src/app/api/partners/[id]/click/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/partners/[id]/image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partners/[id]/image">> = Specific
  const handler = {} as typeof import("../../src/app/api/partners/[id]/image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/partners/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partners/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/partners/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/partners/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partners">> = Specific
  const handler = {} as typeof import("../../src/app/api/partners/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/[id]/mtn/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/[id]/mtn">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/[id]/mtn/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/[id]/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/[id]/stripe">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/[id]/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reservations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reservations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/reservations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reservations/availability/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reservations/availability">> = Specific
  const handler = {} as typeof import("../../src/app/api/reservations/availability/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reservations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reservations">> = Specific
  const handler = {} as typeof import("../../src/app/api/reservations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/shop/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shop/orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/shop/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stringing/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stringing/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/stringing/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stringing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stringing">> = Specific
  const handler = {} as typeof import("../../src/app/api/stringing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/uploads/[name]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/uploads/[name]">> = Specific
  const handler = {} as typeof import("../../src/app/uploads/[name]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(site)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
